name: Codemeet CI

on:
  push:
   branches:
    - main 

jobs:
  build:
      runs-on: ubuntu-latest

      env: 
        VITE_API_URL: http://localhost:8080
 
      steps: 
        - name: checkout code
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4
          with: 
               node-version: 22

        - name:  Install backend dependencies
          run: npm ci --prefix backend
        
        - name: Install frontend dependencies
          run: npm ci --prefix frontend
         
        - name: Build Frontend
          run: npm run build --prefix frontend

        - name: Build backend Docker image 
          run: docker build -t codemeet-backend:ci ./backend

        - name: Build frontend Docker image
          run: docker build -t codemeet-frontend:ci ./frontend

        - name: Run Frontend lint
          run: npm run lint --prefix frontend
          